// Furniture: a furnished farmhouse at evening with a placement ghost, plus furniture icons.
import { chromium } from 'playwright';
import fs from 'node:fs';
const base = process.env.BASE ?? 'http://127.0.0.1:5173/';
const out = 'e2e/out/house';
fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'warning' || m.type() === 'error') errors.push(m.text()); });
await page.goto(base);
await page.waitForTimeout(1200);
const ev = (s) => page.evaluate(s);
await ev(`(async () => {
  const g = new window.__Game({ seed: 3, name: 'Wren', farmName: 'Hollow' });
  for (const t of ['welcome', 'hoe', 'seeds', 'can', 'place', 'lab', 'belts', 'machine', 'power', 'blueprint', 'energy', 'night']) g.flags.add('tip_' + t);
  window.__app.startGame(g, { skin: 2, hair: 9, hairStyle: 'long', shirt: 28, pants: 19 });
  window.S = { g };
  const I = await import('/src/sim/inventory.ts');
  const H = await import('/src/sim/systems/house.ts');
  const P = await import('/src/sim/systems/pet.ts');
  g.flags.add('home_kitchen');
  H.enterHouse(g);
  g.player.x = 9.5; g.player.y = 8.6;
  const put = (id, x, y) => { g.player.inv.add(I.key(id), 1); const e = H.placeDecor(g, id, x, y); if (e) console.log('place fail', id, e); };
  put('f_rug_green', 9, 3); put('f_armchair_rose', 9, 3); put('f_lamp', 10, 3);
  put('f_tank', 2, 8); put('f_bookcase', 12, 7); put('f_fern', 1, 5);
  put('f_paint_meadow', 6, 1); put('f_paint_tower', 9, 1); put('f_banner', 12, 1);
  put('f_petbed', 6, 4); put('f_rug_blue', 9, 7);
  const p = P.petSys(g); p.kind = 'cat'; p.coat = 0; P.adoptPet(g, 'Turnip');
  g.time.min = 20 * 60 + 30;
  g.player.inv.slots[11] = { k: I.key('f_armchair_sage'), n: 1 }; g.player.sel = 11;
})()`);
await page.waitForTimeout(1500);
const scr = await ev(`(() => { const r = window.__app.renderer; const s = r.tileToScreen(4.5, 8.5); return { x: s.x / window.__app.dpr, y: s.y / window.__app.dpr }; })()`);
await page.mouse.move(scr.x, scr.y);
await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/furnished.png` });
await page.mouse.click(scr.x, scr.y);
await page.waitForTimeout(300);
console.log('decor', await ev(`S.g.sys.house.decor.length`), 'pet', JSON.stringify(await ev(`[S.g.sys.pet.map, S.g.sys.pet.x.toFixed(1), S.g.sys.pet.y.toFixed(1), S.g.sys.pet.mode]`)));
console.log('errors', errors.slice(0, 10));
await browser.close();
